/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type TranscriptChunk = {
  _type: "transcriptChunk";
  startSeconds: number;
  text: string;
};

export type Chapter = {
  _type: "chapter";
  startSeconds: number;
  label: string;
};

export type Resource = {
  _type: "resource";
  type: "article" | "video" | "download" | "link" | "github";
  title: string;
  description?: string;
  url: string;
};

export type LearningOutcome = {
  _type: "learningOutcome";
  icon?: string;
  title: string;
  description: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type Module = {
  _type: "module";
  title: string;
  summary?: string;
  lessons?: Array<{
    _key: string;
  } & LessonReference>;
};

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  url: string;
  chapters?: Array<{
    _key: string;
  } & Chapter>;
  chunks?: Array<{
    _key: string;
  } & TranscriptChunk>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  videoUrl: string;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  duration: string;
  isFreePreview?: boolean;
  studentCount?: number;
  notes?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  keyPoints?: Array<string>;
  proTip?: string;
  resources?: Array<{
    _key: string;
  } & Resource>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  level: "Beginner" | "Intermediate" | "Advanced";
  price?: number;
  isPopular?: boolean;
  studentCount?: number;
  learningOutcomes?: Array<{
    _key: string;
  } & LearningOutcome>;
  instructor: InstructorReference;
  category: CategoryReference;
  modules?: Array<{
    _key: string;
  } & Module>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
  icon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  expertise?: string;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = TranscriptChunk | Chapter | Resource | LearningOutcome | LessonReference | Module | Video | SanityImageAssetReference | Lesson | SanityImageCrop | SanityImageHotspot | Slug | InstructorReference | CategoryReference | Course | Category | Instructor | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../sanity/lib/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category" && defined(slug.current)] | order(title asc) {    _id,    title,    "slug": slug.current,    description,    icon {   asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  hotspot,  crop }  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  icon: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    description,    icon {   asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  hotspot,  crop }  }
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  icon: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: INSTRUCTORS_QUERY
// Query: *[_type == "instructor" && defined(slug.current)] | order(name asc) {    _id,    name,    "slug": slug.current,    expertise,    photo {   asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  hotspot,  crop },    bio  }
export type INSTRUCTORS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  expertise: string | null;
  photo: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: INSTRUCTOR_BY_SLUG_QUERY
// Query: *[_type == "instructor" && slug.current == $slug][0]{    _id,    name,    "slug": slug.current,    expertise,    photo {   asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  hotspot,  crop },    bio  }
export type INSTRUCTOR_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  expertise: string | null;
  photo: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: LESSONS_QUERY
// Query: *[_type == "lesson" && defined(slug.current)] | order(title asc) {    _id,    title,    "slug": slug.current,    videoUrl,    poster {   asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  hotspot,  crop },    duration,    isFreePreview,    studentCount,    keyPoints,    proTip  }
export type LESSONS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  videoUrl: string;
  poster: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  duration: string;
  isFreePreview: boolean | null;
  studentCount: number | null;
  keyPoints: Array<string> | null;
  proTip: string | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: LESSON_BY_SLUG_QUERY
// Query: *[_type == "lesson" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    videoUrl,    poster {   asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  hotspot,  crop },    duration,    isFreePreview,    studentCount,    notes,    keyPoints,    proTip,    resources[]{      _key,      type,      title,      description,      url    },    // Reverse reference: find the course(s) that include this lesson in any module    "parentCourses": *[_type == "course" && references(^._id)]{      _id,      title,      "slug": slug.current    }  }
export type LESSON_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  videoUrl: string;
  poster: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  duration: string;
  isFreePreview: boolean | null;
  studentCount: number | null;
  notes: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  keyPoints: Array<string> | null;
  proTip: string | null;
  resources: Array<{
    _key: string;
    type: "article" | "download" | "github" | "link" | "video";
    title: string;
    description: string | null;
    url: string;
  }> | null;
  parentCourses: Array<{
    _id: string;
    title: string;
    slug: string;
  }>;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: LESSON_SLUGS_QUERY
// Query: *[_type == "lesson" && defined(slug.current)]{ "slug": slug.current }
export type LESSON_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: COURSES_QUERY
// Query: *[_type == "course" && defined(slug.current)] | order(title asc) {    _id,    title,    "slug": slug.current,    summary,    coverImage {   asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  hotspot,  crop },    level,    price,    isPopular,    studentCount,    "modulesCount": count(modules),    learningOutcomes[]{      _key,      icon,      title,      description    },    instructor->{      _id,      name,      "slug": slug.current,      expertise,      photo {   asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  hotspot,  crop }    },    category->{      _id,      title,      "slug": slug.current,      icon {   asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  hotspot,  crop }    }  }
export type COURSES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  level: "Advanced" | "Beginner" | "Intermediate";
  price: number | null;
  isPopular: boolean | null;
  studentCount: number | null;
  modulesCount: number | null;
  learningOutcomes: Array<{
    _key: string;
    icon: string | null;
    title: string;
    description: string;
  }> | null;
  instructor: {
    _id: string;
    name: string;
    slug: string;
    expertise: string | null;
    photo: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      alt: string;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  };
  category: {
    _id: string;
    title: string;
    slug: string;
    icon: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      alt: string;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  };
}>;

// Source: ../sanity/lib/queries.ts
// Variable: COURSE_BY_SLUG_QUERY
// Query: *[_type == "course" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    summary,    coverImage {   asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  hotspot,  crop },    level,    price,    isPopular,    studentCount,    learningOutcomes[]{      _key,      icon,      title,      description    },    instructor->{      _id,      name,      "slug": slug.current,      expertise,      photo {   asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  hotspot,  crop },      bio    },    category->{      _id,      title,      "slug": slug.current,      description,      icon {   asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  hotspot,  crop }    },    modules[]{      _key,      title,      summary,      lessons[]->{        _id,        title,        "slug": slug.current,        videoUrl,        poster {   asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  hotspot,  crop },        duration,        isFreePreview,        studentCount,        keyPoints,        proTip      }    }  }
export type COURSE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  summary: string;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  level: "Advanced" | "Beginner" | "Intermediate";
  price: number | null;
  isPopular: boolean | null;
  studentCount: number | null;
  learningOutcomes: Array<{
    _key: string;
    icon: string | null;
    title: string;
    description: string;
  }> | null;
  instructor: {
    _id: string;
    name: string;
    slug: string;
    expertise: string | null;
    photo: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      alt: string;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    bio: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  };
  category: {
    _id: string;
    title: string;
    slug: string;
    description: string | null;
    icon: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      alt: string;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  };
  modules: Array<{
    _key: string;
    title: string;
    summary: string | null;
    lessons: Array<{
      _id: string;
      title: string;
      slug: string;
      videoUrl: string;
      poster: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number;
              height: number;
            } | null;
          } | null;
        } | null;
        alt: string;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      duration: string;
      isFreePreview: boolean | null;
      studentCount: number | null;
      keyPoints: Array<string> | null;
      proTip: string | null;
    }> | null;
  }> | null;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: COURSE_SLUGS_QUERY
// Query: *[_type == "course" && defined(slug.current)]{ "slug": slug.current }
export type COURSE_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: VIDEO_BY_URL_QUERY
// Query: *[_type == "video" && url == $url][0]{    _id,    url,    chapters[]{      _key,      startSeconds,      label    },    chunks[]{      _key,      startSeconds,      text    }  }
export type VIDEO_BY_URL_QUERY_RESULT = {
  _id: string;
  url: string;
  chapters: Array<{
    _key: string;
    startSeconds: number;
    label: string;
  }> | null;
  chunks: Array<{
    _key: string;
    startSeconds: number;
    text: string;
  }> | null;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: VIDEOS_QUERY
// Query: *[_type == "video"] | order(url asc) {    _id,    url,    "chaptersCount": count(chapters),    "chunksCount": count(chunks)  }
export type VIDEOS_QUERY_RESULT = Array<{
  _id: string;
  url: string;
  chaptersCount: number | null;
  chunksCount: number | null;
}>;

